Description of round2
round2
PURPOSE
SYNOPSIS
function z = round2(x,y) %#eml
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ota_commu_isr_trafsim --------------------------------------------------------------------------
rxtx_module_isr_trafsim --------------------------------------------------------------------------
script_recv_app --------------------------------------------------------------------------
cross_gest_isr_trafsim --------------------------------------------------------------------------
grid_isr_trafsim --------------------------------------------------------------------------
launch_car_isr_trafsim --------------------------------------------------------------------------
launch_isr_trafsim --------------------------------------------------------------------------
view_offline_isr_trafsim --------------------------------------------------------------------------
printset_isr_trafsim --------------------------------------------------------------------------
move_isr_trafsim --------------------------------------------------------------------------
create_L_isr_trafsim --------------------------------------------------------------------------
create_layer_isr_trafsim --------------------------------------------------------------------------
writeM_isr_trafsim --------------------------------------------------------------------------
write_MM_isr_trafsim --------------------------------------------------------------------------
write_layer_isr_trafsim --------------------------------------------------------------------------
write_profile_isr_trafsim --------------------------------------------------------------------------
round_gest_isr_trafsim --------------------------------------------------------------------------
run_isr_trafsim --------------------------------------------------------------------------
SOURCE CODE
function z = round2(x,y)    %#eml
z = round(x/y)*y;
end