%--------------------------------------------------------------------------
%                           ISR-TrafSim v2.0
%                        Copyright (C) 2010-2013
%
%--------------------------------------------------------------------------
% This Matlab file is part of the ISR-TrafSim: a Matlab
% library for traffic simulation and pose estimation in Urban environments,
% namely roundabouts and crossroads.
%
% http://www.isr.uc.pt/~conde/isr-trafsim/
%
%-CITATION---------------------------------------------------------------------------
% If you use this software please cite one of the following papers:
% 1) L.C.Bento, R.Parafita, S.Santos and U.Nunes, An Intelligent Traffic Management
% at Intersections legacy mode for vehicles not equipped with V2V and V2I Communications,
% 16th IEEE Int.Conf. Intelligent Transportation Systems, Netherlands, 2013.
% 2) L.C.Bento, R.Parafita and U.Nunes, Inter-vehicle sensor fusion for accurate vehicle
% localization supported by V2V and V2I communications, 15th IEEE Int.Conf. Intelligent
% Transportation Systems, USA, 2012.
% 3) L.C.Bento, R.Parafita and U.Nunes, Intelligent traffic management at intersections
% supported by V2V and V2I communications, 15th IEEE Int.Conf. Intelligent
% Transportation Systems, USA, 2012.
%
%-DESCRIPTION------------------------------------------------------------------------
%
%
%-DISCLAIMER-------------------------------------------------------------------------
% This program is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% You can use this source code without licensing fees only for NON-COMMERCIAL research
% and EDUCATIONAL purposes only.
% You cannot repost this file without prior written permission from the authors.
%
%-AUTHORS------------------------------------------------------------------
%   Urbano Nunes*
%   Luis Conde Bento**
%   Ricardo Parafita*
%   Sergio Santos*
%
%  *Institute of Systems and Robotics   - University of Coimbra
% **School of Technology and Management - Polytechnic Institute of Leiria
%--------------------------------------------------------------------------

function ota_commu_run_isr_trafsim(max_time, log_file)
global current_time edebug fdebug size_Event_list Event_list;

% Event driven simulation loop
size_Event_list=0;
while 1
    [min_instant, min_index] = min([Event_list(:).instant]);
    if isempty(min_instant)
        break;
    end
    if min_instant > max_time
        break;
    end
    
    NewEvents = action(Event_list(min_index), log_file);      % Get new events from executing the latest 'action'
    current_time = min_instant;
    Event_list(min_index) = [];                     % Delete the latest event which has been just executed.
    if(size(NewEvents,1)>1)
        NewEvents=NewEvents';
    end
    Event_list = [NewEvents Event_list];   % Append new events generated by executing the latest event
    size_Event_list=size(Event_list);
    
    if fdebug
        if size_Event_list(2)
            disp('BEGIN ***************************')
            for i=1:size_Event_list(1)
                if 1 %~strcmp(Event_list(i).type, 'backoff') && ~strcmp(Event_list(i).type, 'wait_for_channel') && ~strcmp(Event_list(i).type, 'backoff_start')
                    disp([num2str(Event_list(i).node,2) ' ' Event_list(i).type ' ' num2str(Event_list(i).instant)]);
                end
            end
            disp('END ############################')
        end
        
    end
end

return;