Description of carrier_sense
carrier_sense
PURPOSE
check if the channel is busy
SYNOPSIS
function busy = carrier_sense(rv)
DESCRIPTION
 check if the channel is busy
CROSS-REFERENCE INFORMATION
This function calls:
recv_power send packet at PHY layer
This function is called by:
script_backoff script_backoff;
script_backoff_start script_backoff_start
script_wait_for_channel script_wait_for_channel
SOURCE CODE
function busy = carrier_sense(rv)
% check if the channel is busy
global node;
global white_noise_variance;
global rmodel cs_threshold;
Pr = 0;
I = find(node(:, 3)>0);
for i=1:length(I)
   tx1 = I(i);
   if tx1 == rv, continue; end
   Pr = Pr + recv_power(tx1, rv, rmodel);
end
% N0 = abs(random('norm', 0, white_noise_variance));
N0 = white_noise_variance;
% Pr+N0
if (Pr+N0) > cs_threshold
    busy = 1;
else
    busy = 0;
end
return;