Description of friis
friis
PURPOSE
Friis free space propagation model:
SYNOPSIS
function Pr = friis(Pt, Gt, Gr, lambdacommu, Lcommu, Dcommu)
DESCRIPTION
 Friis free space propagation model:
        Pt * Gt * Gr * (lambdacommu^2)
  Pr = --------------------------
        (4 *pi * Dcommu)^2 * Lcommu
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
log_normal_shadowing log normal shadowing radio propagation model:
parameter clear;
recv_power send packet at PHY layer
tworay if Dcommu < crossover_dist, use Friis free space model
SOURCE CODE
function Pr = friis(Pt, Gt, Gr, lambdacommu, Lcommu, Dcommu)
% Friis free space propagation model:
%        Pt * Gt * Gr * (lambdacommu^2)
%  Pr = --------------------------
%        (4 *pi * Dcommu)^2 * Lcommu
M = lambdacommu / (4 * pi * Dcommu);
Pr = Pt * Gt * Gr * (M * M) / Lcommu;
return;