Description of new_id
new_id
PURPOSE
return a new id for node i
SYNOPSIS
function [newid] = new_id(i);
DESCRIPTION
 return a new id for node i
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
script_recv_mac script_recv_mac;
script_recv_net script_recv_net
script_send_mac script_send_mac;
script_send_net2 script_send_net2;
script_timeout_rreq script_timeout_rreq
SOURCE CODE
function [newid] = new_id(i);
% return a new id for node i
global Nnodes packet_id;
newid = 0;
if i<=0 | i>Nnodes, return; end
packet_id(i) = packet_id(i) + 1;
newid = packet_id(i);
return;